[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true

# Network configurations
[rpc_endpoints]
coston2 = "https://coston2-api.flare.network/ext/C/rpc"
sepolia = "https://sepolia.drpc.org"
lisk = "https://rpc.sepolia-api.lisk.com"
local = "http://127.0.0.1:8545"

evm_version = "shangai"